### ISSUE TITLE
Java records as repository method return types

### ISSUE THREAD

**Issue by njr-11** [jakartaee/data-api#9]
Note: Supporting Java records as entities would of course also be nice, but that is a different matter to be addressed in a different issue, if that is even possible with JPA/Jakarta Persistence.

This current proposal only covers repository method return types and is what is currently possible with JPA/Jakarta Persistence.  It remains useful regardless of whether the former also happens at some point.

**Description**

As a:

- [ ] Application user/user of the configuration itself
- [x] API user (application developer)
- [ ] SPI user (container or runtime developer)
- [ ] Specification implementer

...I need to be able to:
write repository methods that retrieve results as Java records

...which enables me to:
more easily work with the results, avoid cumbersome code to perform conversions on my own, and take advantage of more modern programming models with less boilerplate code.

JPQL has the ability to retrieve a subset of entity attributes and return them as instances of a different type, given a constructor on that type which supplies the necessary subset of attributes as parameters.  Conveniently, this mechanism can be used to get Jakarta Persistence providers to create instances of Java records.  If we introduce an annotation to allow for selecting a ordered subset of entity attributes (the constructor parameters for the Java Record), then this ability of JPQL can be leveraged to support Java records as return types from repository queries.

As an example, if there is a repository for an `Employee` entity type and you would like to write a repository method that retrieves `Name` records (which are only the first and last name of the employee),

```
record Name(String first, String last) {}
```

then you could write a repository method like the following,

```
@Select({"firstName", "lastName"})
Name[] findBy...
```

and the Jakarta Data implementation could generate JPQL for it such as,

```
SELECT NEW org.eclipse.example.Name(o.firstName, o.lastName) FROM Employee o ...
```

which would cause the Jakarta Persistence/JPA provider to retrieve the results as an ordered list of Name records instead of Employee (the entity type).

There is a possible case where the method return type is parameterized and obscures the desired type at run time.  One way to address that would be with an optional annotation, such as,

```
@Select({"firstName", "lastName"})
@Result(Name.class) // identifies the type when it cannot be inferred
List<Name> findBy...
```

Other random ideas building on the above ...

I can also think of a number of other interesting things we might choose to do with a `@Select` annotation if we added it for the records scenario, although none of the following are why I'm writing this issue.  These could be included or not.

Returning a single attribute only,

```
@Select("lastName")
List<String> findBy...
```

Specifying that you only want distinct values for an attribute,

```
@Select(distinct = true, value = "firstName")
List<String> findBy...
```

Or even applying an aggregate function,

```
@Select(function = Aggregate.COUNT, distinct = true, value = "firstName")
int findBy...
```

Another possibility that you could do with a Select annotation is specifying two attributes where the first is an Id, obtaining the results as a LinkedHashMap (preserves order),

```
@Select({ "productId", "price" })
Map<String, Float> findBy...
```

Again, the main purpose is the Java records scenario, not these latter scenarios, but I wanted to write them down while I had them in mind in case they are of any interest.

**Comment by beikov** [comment]
IMO projections should be left to technologies like [Blaze-Persistence Entity-Views](https://github.com/Blazebit/blaze-persistence#entity-view-usage), although I don't have a strong opinion.

It would be important though that this specification comes up with a way/extension that allows a technology like Entity-Views to provide the implementation for such a method, if it claims responsibility for it e.g. based on the return type, annotation or whatever. Currently, integration with a repository technology usually requires a dedicated module that work with lots of internals. I'd love to have a defined SPI that I can implement for this purpose instead.

**Comment by keilw** [comment]
>Note: Supporting Java records as entities would of course also be nice, but that is a different matter to be addressed in a >different issue, if that is even possible with JPA/Jakarta Persistence.
That's a good question, I could not spot any request in the Jakarta Persistence tracker, if it exists, please point to it.

While this spec and API still evolves, it does not make much sense to introduce something that JPA does not support yet, but maybe it's considered for a Jakarta EE 11 or higher update to Persistence?

**Comment by otaviojava** [comment]
IMHO: We should focus on entities as persistence layer abstraction.
If the implementation supports immutable entities such as records, it will be accessible to each vendor.
I am afraid of making it mandatory, primarily because JPA does not support and they don't have a plan for it, AFIK.

**Comment by njr-11** [comment]
Cancelling this because there is no interest in doing it.
